//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : GruppeC
//  @ File Name : RoadNetwork.h
//  @ Date : 29.04.2019
//  @ Author : 
//
//


#if !defined(_ROADNETWORK_H)
#define _ROADNETWORK_H

#include "Road.h"
#include "Junction.h"

class RoadNetwork
{
public:
	bool register(Road road);
	bool register(Junction junction);
	Junction *junctions;
private:
	Road *roads;
};

#endif  //_ROADNETWORK_H
