//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : GruppeC
//  @ File Name : Junction.cpp
//  @ Date : 29.04.2019
//  @ Author : 
//
//


#include "Junction.h"
#include "RoadNetwork.h"
#include "Road.h"

void Junction::Junction(Point2D position, RoadNetwork network)
{
}

bool Junction::join(Road road, bool atStart)
{
}

