//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : GruppeC
//  @ File Name : Road.h
//  @ Date : 15.04.2019
//  @ Author : 
//
//


#if !defined(_ROAD_H)
#define _ROAD_H

#include "Junction.h"
#include "Vehicle.h"

class Road {
public:
    void Road(Junction start, Junction end);
    double getLength();
    bool addVehicle(Vehicle veh, bool atStart);
    bool removeVehicle(Vehicle veh);
private:
    double length;
    Junction *startNode;
    Junction *endNode;
    Vehicle *vehicles;
};

#endif  //_ROAD_H
