//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : GruppeC
//  @ File Name : RoadNetwork.cpp
//  @ Date : 29.04.2019
//  @ Author : 
//
//


#include "RoadNetwork.h"
#include "Road.h"
#include "Junction.h"

bool RoadNetwork::register(Road road)
{
}

bool RoadNetwork::register(Junction junction)
{
}

