//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : GruppeC
//  @ File Name : Road.cpp
//  @ Date : 15.04.2019
//  @ Author : 
//
//


#include "Road.h"
#include "Junction.h"
#include "Vehicle.h"

void Road::Road(Junction start, Junction end) {
}

double Road::getLength() {
}

bool Road::addVehicle(Vehicle veh, bool atStart) {
}

bool Road::removeVehicle(Vehicle veh) {
}

