//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : GruppeC
//  @ File Name : Vehicle.cpp
//  @ Date : 15.04.2019
//  @ Author : 
//
//


#include "Vehicle.h"
#include "Road.h"

double Vehicle::getPosition() {
}

double Vehicle::getSpeed() {
}

void Vehicle::setSpeed(double newSpeed) {
}

bool Vehicle::setRoad(Road road) {
}

