// Generated by Structorizer 3.29-09 
#define _CRT_SECURE_NO_WARNINGS
#include <iostream>
#include "Turtleizer.h"

// program Square 
int main(void)
{
	// TODO: Check and accomplish variable declarations: 
	int length = 0; 
	
	std::cout << "Bitte Kantenlaenge des Quadrats eingeben: ";
	std::cin >> length;
	for (int i = 1; i <= 4; i += (1))
	{
		forward(length); // color = ffffff
		right(90);
	}
	
	Turtleizer::awaitClose();

	return 0;
}
